services:

  mysql:
    image: mysql:8.3.0
    container_name: newsseug-mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
      MYSQL_DATABASE: newsseug
    networks:
      - newsseug-net

  redis:
    image: redis:latest
    container_name: newsseug-redis
    ports:
      - "6377:6379"
    networks:
      - newsseug-net

networks:
  newsseug-net:
    driver: bridge